### PR TITLE
Customize display

### PR DESCRIPTION
**Pull request by Lerrissirrel**

### CODE REVIEW

**Comment by ThermoMan** [comment]
Drat, I've been away from Git for so long I forgot how to use it.  And I
think I broke it.  I had a hard drive replacement a while back and although
I still have my local Git repository the GUI won't let me do anything.  I
get a non specific error message.  I even uninstalled and reinstalled and
tried to do a clone from scratch and had no joy.

On my local machine I was doing all my development work in SVN and when I
had it at a good place I'd migrate it to Git and update (which I think I
had to do in two steps.  A commit and then a push.  I can't even find push
on the menu in the gui any more.  Skillz, use them or lose them.  sigh.)

Anyway, I have found that my local copy in SVN and in Git are very
different from each other.  I want to get them synced and then look at what
you've been recently working on, because a causal review looks like
something I want in mine.

Is there a good place to look for an error message in Git?  I've viewed the
log, but nothing says "ERROR" (they all say "INFO"), the worst looking
message is something about a proxy and I'm not using one of those.

**Comment by Lerrissirrel** [comment]
Funny, I've been having the same thing.  (problems remembering how to use git)  I spent a few hours last night trying to figure out how to reconcile two of my branches.  I had also started with svn and its (sort of) integration with git.  I ended up having more problems there, even though I found svn much more intuitive than git.

Is it possible that the application has lost your github login info?  I'm not even close to a git expert, but if you post the error you're getting, I might be able to help.

Good luck!

**Comment by ThermoMan** [comment]
Part of my problem may be this used to be on the D:\ and I moved it to the C:\ without doing any changes to the .git files.
I uninstalled and reinstalled and logged out and back in again.  I even tried deleting my local files (I have a backup) and recopying them from the server.  The lack of informative error messages is frustrating.  The only suggestion is that I might need to open a command line (with no hint what to do with it)

**Comment by ThermoMan** [comment]
Aha, I found the error.  Sadly I have no clue how to fix it.

git.exe clone --verbose --progress --recursive "https://github.com/ThermoMan/Thermostat-Tracking.git" Thermostat-Tracking
Cloning into 'Thermostat-Tracking'...
error: Unable to create C:/Users/User/Git/Thermostat-Tracking/.git/HEAD

**Comment by Lerrissirrel** [comment]
It almost sounds like a permissions problem?  Does any of that directory hierarchy exist already?  Can you create (manually) anything in there?

**Comment by ThermoMan** [comment]
I tried in an existing and in a new directory tree.  I even tried on C:\ root.  It creates the .git sub-directory and then fails with that HEAD thing (is that a directory or a file?)

**Pull request closed without merging**
